// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:77972082-41ad-468b-8196-9c315d1d5817",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wvbHTg87C",
    "aws_user_pools_web_client_id": "1lh70o3ve4o9225eu71719dhgv",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://o2kbnb6rzjdr5bo6n3jdn5phu4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
